### ISSUE TITLE
Doesn't work on IE11

### ISSUE THREAD

**Issue by ritz078** [airbnb/react-dates#1076]
One of the dependencies https://github.com/airbnb/react-with-styles-interface-css , uses `Object.assign` that is not supported by IE11. I have opened a PR https://github.com/airbnb/react-with-styles-interface-css/pull/15 to fix that.

I know this can be done by changing webpack config and polyfilling but I think this would be a better fix.

**Comment by ljharb** [comment]
Indeed, react-dates requires using https://npmjs.com/airbnb-browser-shims or the equivalent to ensure that all browsers that can be supported are.

Thanks for the PR - anything we can fix, we certainly will, but running an app without polyfills isn’t a good idea anyways.

**Comment by tommmyy** [comment]
@ljharb SingleDatePicker, unfortunately, does not work in IE 11. 

I tried in my app with https://npmjs.com/airbnb-browser-shims and even on your storybook: http://airbnb.io/react-dates/?selectedKind=SingleDatePicker%20%28SDP%29&selectedStory=default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

After click on Calendar the Input loses focus and calendar is closed. Due to that, you can't select a date nor switch a month.

**Comment by i2chris** [comment]
Is there anyway around this?  I'd be suprised if airbnb didn't make it work with IE11

**Comment by ljharb** [comment]
I believe this is a bug fixed in master but unreleased (and thus unpublished to storybook).

As to the original issue, that’s been closed by #356.
