### ISSUE TITLE
remove extra padding. 

### ISSUE THREAD

**Issue by maxlibin** [airbnb/react-dates#1226]
https://github.com/airbnb/react-dates/blob/6a19133b6138cddadb9a145bf738e3e5542807e7/src/components/DayPicker.jsx#L45

As I understand the wrapper width for DayPicker added some extra padding, but is there a option to remove this?

<img width="81" alt="screen shot 2018-06-22 at 4 23 14 pm" src="https://user-images.githubusercontent.com/1277038/41766105-a349ac96-7638-11e8-8744-d09996d9a257.png">

**Comment by maxlibin** [comment]
```
.DayPicker {
 // Extra margin added by calendar plugin ====
  $padding: 26px;

  margin-top: -$padding;
  margin-left: -$padding; 

  > div {
    transform: translate($padding / 2, $padding / 2);
  }
}
```

This is the hacky way, but still I think we need a way to remove these paddings easily, adding a prop example. wrapperPadding={xxx}

**Comment by majapw** [comment]
@maxlibin yes! it would be good to get this padding customizable easily via a prop. This hasn't been high on my priority list, but I'd be happy to accept a PR (otherwise, it'll probably get done eventually). The only tricky thing here is that the sliding animation will have to be updated to work with the prop.
