### ISSUE TITLE
Uncaught TypeError: onOutsideClick is not a function

### ISSUE THREAD

**Issue by huchenme** [airbnb/react-dates#1227]
This error happens if I have 2 DatePicker on the app, one of them have `withPortal` equal to true.

demo: https://codesandbox.io/s/725j44217x

**Comment by hrmoller** [comment]
@huchenme it even happens if you have just one DatePicker with `withPortal` set to `true` but then first when a date is selected: https://codesandbox.io/s/pkoj9x5mym

**Comment by huchenme** [comment]
If I have a <SingleDatePicker/> with some other <SingleDatePicker withPortal />, and open <SingleDatePicker/> date selector, sometimes it takes me 3 outside clicks to close the opened date selector.

**Comment by majapw** [comment]
I think this is related to the `react-outside-click-handler` upgrade (previously `onOutsideClick` wasn't required). Let me patch that real quick.

**Comment by huchenme** [comment]
thanks @majapw

**Comment by fuse-mars** [comment]
@majapw and @huchenme looks like the cause is from these two lines
* https://github.com/airbnb/react-dates/blob/master/src/components/DateRangePicker.jsx#L396
* https://github.com/airbnb/react-dates/blob/master/src/components/DateRangePicker.jsx#L529

Using `() => {}` instead of `undefined` should fix the issue

**Comment by ljharb** [comment]
#1239 seems like it might address it.
