### ISSUE TITLE
Make date cell render configurable

### ISSUE THREAD

**Issue by evgenTraytyak** [airbnb/react-dates#127]
<img width="301" alt="screen shot 2016-10-16 at 17 13 40" src="https://cloud.githubusercontent.com/assets/6050297/19418019/06154366-93c4-11e6-9e08-29937ea493f4.png">

I want to render some additional information under the date. Price for example.
Does anybody have any ideas how to do it?

**Comment by senseluo** [comment]
voting for this feature

**Comment by ljharb** [comment]
@senseluo a +1 reaction on the original post is always sufficient to "vote" for a feature; +1 comments and similar don't add any value. Since you've already done that, I'll delete your comment as well as my reply, so as to keep the thread clean. Thanks!

**Comment by majapw** [comment]
This has been been fixed by #283 (I must have missed this issue) but you can pass in a function to the `renderDay` prop to accomplish this. The function will receive the moment object representing the day as an argument. 

Check out https://github.com/airbnb/react-dates/blob/master/stories/DateRangePicker_day.js#L72 for an example of how to use it.

**Comment by sunlee-newyork** [comment]
I tried to return a React element but it only works by returning a string. Is there a way to return a React element instead?
