### ISSUE TITLE
Support `required` attribute on inputs

### ISSUE THREAD

**Issue by FezVrasta** [airbnb/react-dates#136]
Seems the MVP to have at least the ability to set `required` to the `input` elements.

**Comment by majapw** [comment]
Feel free to PR this in if you need it for your usecase, but looking at https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input, the `required` attribute is only supported in IE10+ and not at all supported in Safari so it doesn't really work for our environment. The nice thing though is since this is a React component, in theory your entire form will be wrapped in a react component and you'll be able to disable submission until you have dates entered.

**Comment by FezVrasta** [comment]
This is the situation: http://caniuse.com/#feat=form-validation

It's an HTML5 standard and a lot of websites use it so it's definitely something that would be nice to have.

I know I can disable the form programmatically (I did it using `setCustomValidity` on the `submit` event), but my request is mostly an accessibility reason. the `required` attribute is supported by the recent browsers and make it easy to interact with forms with screen readers or via keyboard.

**Comment by majapw** [comment]
Sounds good to me! 👍 We'll be happy to accept a PR to add this functionality. It would probably be pretty similar to adding the disabled prop (https://github.com/airbnb/react-dates/pull/5)
