### ISSUE TITLE
zIndex dosen't work properly on DateRangePicker_picker

### ISSUE THREAD

**Issue by joan17cast** [airbnb/react-dates#1460]
I want to show the daterangepicker panel above the modal, but the zindex is not correct.

![image](https://user-images.githubusercontent.com/29452333/48253526-c113bb80-e407-11e8-85a9-96325915dee1.png)

In this photo you can see the zIndex of the modal is 1300

![image](https://user-images.githubusercontent.com/29452333/48253361-64180580-e407-11e8-845f-8e7e19725286.png)

Now you can see zIndex from daterangepicker is 1

![image](https://user-images.githubusercontent.com/29452333/48253667-28ca0680-e408-11e8-8d44-bc71cc338b91.png)
So I think this part of the code does not work properly

If someone can help me to solve this issue in my project or something

![image](https://user-images.githubusercontent.com/29452333/48253999-01276e00-e409-11e8-8366-f94b8fa15013.png)

Thank you all!

**Comment by majapw** [comment]
Hmm, the pattern you're using is a bit of an unexpected one I think---namely that you're launching a modal (the `withPortal` version of the `DateRangePicker`) inside of a modal, which can be complicated. 

I wouldn't update the `zIndex` on the `DateRangePicker_picker` class because that's the style used for all pickers, inline and with portals, but perhaps overriding the `zIndex` to `9999` or something similar on the `.DateRangePicker_picker__portal` class would fix your issue.

**Comment by joan17cast** [comment]
@majapw thanks for your rensponse. 
You can explain me, how i overriding the `zIndex `on `.DateRangePicker_picker__portal`?
because i try with that code, but isn`t work.
![image](https://user-images.githubusercontent.com/29452333/48338375-c53d1480-e665-11e8-864d-cd25301b455f.png)

![image](https://user-images.githubusercontent.com/29452333/48338392-d84fe480-e665-11e8-81a3-afb515a72a0a.png)
