### ISSUE TITLE
position absolute on Week headers places them on top of everything.

### ISSUE THREAD

**Issue by revant9c** [airbnb/react-dates#1462]
I am using custom month and and year drop downs  or DayPickerSingleDateController. Week headers are inside one wrapper(div) and rest of the calendar inside another wrapper(div). Week headers are absolute positioned and they are always on top of everything. So when the drop down is open, the week headers are on top of them. Here's an image: 

![screen shot 2018-11-11 at 10 17 15 pm](https://user-images.githubusercontent.com/37884853/48329924-a015bb00-e5ff-11e8-85b8-634543f244fa.png)

 I have tried almost everything but can't make it work.

**Comment by deep-coder** [comment]
This is because z-index of Week div is greater than the calendar div to make week headers visible as week div is absolute positioned . There is way to solve it not sure this is the right way but it will work. You need to increase the z-index of calendar wrapper but this will change the stacking context and week div will get hide behind calendar wrapper. So to make week header visible, you need to make background-color of calendar wrapper transparent.hope this helps :)

**Comment by Zara603** [comment]
> .CalendarMonth {
>   background: transparent;
> }

Thanks so much, saved me
