### ISSUE TITLE
I have a custom input which controls the DayPickerSingleDateController. I want to keep focus on the input when I am interacting with the date picker.  

### ISSUE THREAD

**Issue by revant9c** [airbnb/react-dates#1570]
**react-dates version**
e.g. latest

**Describe the bug**
I have a custom input which controls the DayPickerSingleDateController. I want to keep focus on the input when I am interacting with the date picker. Right now, the input loses focus when interacting with the date picker. This issue is present on Storybook too. 

**Source code (including props configuration)**
```
<DayPickerSingleDateController
          date={dateObj ? moment(dateObj, 'MM/DD/YYYY') : null}
          onDateChange={this.handleDateChange}
          onFocusChange={this.handleFocusChange}
          focused={focused}
          numberOfMonths={1}
          hideKeyboardShortcutsPanel
          noBorder
          isOutsideRange={this.isOutsideRange}
          onOutsideClick={toggleCal}
          renderMonthElement={({month, onMonthSelect, onYearSelect}) =>
            this.renderMonthYearElement(month, onMonthSelect, onYearSelect)
          }
          onNextMonthClick={this.handleCalendarNavigation}
          onPrevMonthClick={this.handleCalendarNavigation}
        />
```

**Screenshots/Gifs**
Here's a GIF showing that issue
https://media.giphy.com/media/XIRInGpdSb6VKco8zO/giphy.gif

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.3
 - Browser: chrome
 - Version: latest

**Is the issue reproducible in Storybook?**
https://airbnb.io/react-dates/?selectedKind=DayPickerSingleDateController&selectedStory=with%20custom%20input&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by smithaitufe** [comment]
Hi, I can see this issue is still open. 

Have you found a way around it?

**Comment by erin-doyle** [comment]
This is deliberate.  The focus needs to move to the element the user is interacting with.  If they are interacting with the date picker then that's where the focus will be.  There are accessibility implications if you trap the focus on the input you won't be allowing a user using a keyboard or screen reader to navigate to the Date Picker in order to select a date.

If I'm misunderstanding what you're trying to explain or accomplish please feel free to reopen this and clarify further.
