### ISSUE TITLE
Width calculate bug in modal view

### ISSUE THREAD

**Issue by subicura** [airbnb/react-dates#177]
If react-dates rendered in hidden element(like modal), initializeDayPickerWidth method set dayPickerWidth zero. So, next and prev method is not working normally.

This issue related with #163

With tether, date picker popup will render in body element. But now, react-dates render in hidden(modal) element.

Calculate element size method should be fixed.

I tested it with bootstrap-modal.

**Comment by subicura** [comment]
$('.CalendarMonth')[0].offsetWidth => 0

**Comment by majapw** [comment]
How are you showing/hiding your modal? Are you using `display: none` to do so? 

I am thinking that we could use `props.hidden` to help alleviate this problem. Maybe if instead of calling `initializeDayPickerWidth` on `componentDidMount`, we initalized it in `componentWillReceiveProps` and only when the DayPicker is about to be opened that would help to address this issue.

**Comment by subicura** [comment]
Popup element uses `display: none` and `display: block`.

I'm thinking `props.hidden` is not good solution. Because I use same form in popup and plain page. Change prop solution is little complicated.

jQuery's `width()` method can calculate hidden(display:none) element's size correctly. I'm thinking change calculate method. It doesn't need any more code. (like props..)

**Comment by majapw** [comment]
I don't really see us introducing jquery back into this library. `props.hidden` is not something that you as a consumer have to set, but rather is an internal prop to the `DayPicker` from the `DateRangePicker` based on whether or not the `DayPicker` is showing yet. If we call `initializeDayPickerWidth` when `hidden` is about to change from false to true instead of on `componentDidMount`, then I believe this would solve the problem. This could even be a fix for https://github.com/airbnb/react-dates/issues/46.

**Comment by subicura** [comment]
OK. I understand. It's good. Thanks! :)

**Comment by subicura** [comment]
any news??

**Comment by majapw** [comment]
Hi @subicura, can you check if #196 helps?

**Comment by subicura** [comment]
@majapw It works! Now, next and prev method is OK. Thanks! 👍

**Comment by majapw** [comment]
Awesome. 👍 I will merge that in ASAP and do a release.
