### ISSUE TITLE
Current month off screen on small screens (mobile, etc)

### ISSUE THREAD

**Issue by duzenko** [airbnb/react-dates#179]
![untitled](https://cloud.githubusercontent.com/assets/1481807/20220936/168147c6-a838-11e6-8067-a28d76cba529.png)

**Comment by jpollard-cs** [comment]
in this case you'd probably want to use the `withPortal` option - in my opinion this should apply automatically on smaller screens (so maybe worth exploring that), but for now I believe this behavior is expected and you'll need to detect screen size and programatically set the `withPortal` option

disclaimer: I haven't actually used `withPortal`, but I believe this is the expected behavior

**Comment by duzenko** [comment]
How do I detect screen size in react?

**Comment by jpollard-cs** [comment]
practically speaking for this case you may just want to use the window object (kit's breaking out of the React abstraction, but there's no out of the box abstraction/solution here yet)

**Comment by majapw** [comment]
I think we are move to an attached (no portal) single month datepicker on small screens at Airbnb, but this has also been in experimentation for a while. We are not going to detect screen-size for you now or ever and decide what you want to do there, because I feel like that may be different from app to app. Basically, it's going to be on you to detect screen-size and adjust the properties accordingly. 

Agree with @jpollard-cs that using the window object coupled with matchMedia is probably the best way to do this right now. :)

**Comment by duzenko** [comment]
Sorry, didn't help
![untitled](https://cloud.githubusercontent.com/assets/1481807/20237421/a53d3ac2-a8da-11e6-9843-1a86c001f27c.png)
```
            <SingleDatePicker
              id='qweqwe'
              onDateChange={this.onDateChange}
              onFocusChange={this.onFocusChange}
              focused={focused}
              date={date}
              withPortal={true}
              isOutsideRange={() => false}
            />    
```

**Comment by duzenko** [comment]
Temporary workaround:
```
    var mobile = window.innerWidth < 400;
...
            <SingleDatePicker
              id='qweqwe'
              onDateChange={this.onDateChange}
              onFocusChange={this.onFocusChange}
              focused={focused}
              date={date}
              numberOfMonths={mobile ? 1: 2}
              withPortal={mobile}              
              isOutsideRange={() => false}
            />     
```

**Comment by majapw** [comment]
Hi @duzenko, what you have is not a workaround, that is the way we recommend you do things. `numberOfMonths` is an explicit prop and there is no logic to change the number of months based on screensize. 

You can also use the vertical orientation on small screens. There's lots of options for fitting your datepicker to small screens.
