### ISSUE TITLE
Cannot read property 'getBoundingClientRect' of null at DateRangePicker.responsivizePickerPosition

### ISSUE THREAD

**Issue by trongthanh** [airbnb/react-dates#181]
Version: react-dates@4.0.0

How to reproduce:

- Render SingleDatePicker with portal: `<SingleDatePicker withPortal={true} />`
- Make sure the modal date picker overlay is closed.
- Resize the browser
- This error is thrown:
```
Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null
    at DateRangePicker.responsivizePickerPosition ((index):54459)
```

AFAIK, The `dayPickerContainer` is not in the DOM when overlay is closed, so always get reference to it in the resize handler is naive. Besides, `componentWillUnmount`(where the resize hook is removed) doesn't work with the Portal transport when the picker is closed.

**Comment by Ikana** [comment]
I get the same error, but on the storybook, under the section SingleDatePicker specifically under 
- horizontal with portal
- horizontal with fullscreen portal
- vertical with full screen portal

**Comment by majapw** [comment]
Okay, I understand this problem. Responsivizing the daypicker doesn't make sense when we are using a portal (since the daypicker is not rendered when it is not showing) also because the daypicker is positioned in the center of the screen. We should conditionally call the function only when `withPortal` and `withFullScreenPortal` are both false.
