### ISSUE TITLE
DayPicker does not highlight day when clicked

### ISSUE THREAD

**Issue by cemremengu** [airbnb/react-dates#204]
Is there a way to make the [DayPicker](http://airbnb.io/react-dates/?selectedKind=DayPicker&selectedStory=default&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel) highlight the date when clicked ?

**Comment by majapw** [comment]
Hi @cemremengu, the `DayPicker` is a fully controlled but vanilla component that doesn't have any of the logic built out for you. It is expected that it does not highlight the date when clicked.

It was intended for you to use the day interaction callbacks (`onDayMouseEnter`, `onDayMouseLeave`, `onDayMouseClick`) and the `modifiers` prop to set up your own interactions.

There is also a currently undocumented component (my holiday goal is to improve the react-dates documentation) called `DayPickerRangeController` that will probably help you as well. This has all the range logic set up for you (I plan on creating a `DayPickerSingleDateController` eventually in the same style) but does not include the inputs.

**Comment by neekey** [comment]
Hi @majapw, just like what I asked in https://github.com/airbnb/react-dates/issues/139, I am actually asking for a feature that I can use the dateRangePicer without the associated inputs

The reason I can't just use the DayPicker directly is that I need the functionality of picking "date range" instead of just picking one date.

My case is like:

![image](https://cloud.githubusercontent.com/assets/499870/21168653/fd6337a4-c209-11e6-9d10-c3c1542e7cbc.png)

I get a date range dropdown, and when the "custom range" is clicked, I want to show the dateRangePicker:

![image](https://cloud.githubusercontent.com/assets/499870/21168672/2147e098-c20a-11e6-89b5-b23130087e71.png)

and the dateRangePicker will just be responsible for providing me the date range user selected, regardless where or how to render the selected date range.

For the moment, what I did is use css to hide the inputs:

```css
.DateRangePicker {
  display: none;
}
```

and use `focusedInput` to control the open state of the calendar.

Let me know if I miss anything or if there's already a better way to work around it. Thanks

**Comment by majapw** [comment]
Hi @cemremengu, that's why I recommend the `DayPickerRangeController`. It takes in a `startDate`, `endDate`, and `focusedInput` just like the `DateRangePicker`, but is just the calendar... no inputs! :) Of course, from your screenshot, it looks like you are specifically looking for a portal implementation which you would have to do on your own if you use the `DayPickerRangeController`. There's no documentation for it yet, but it is being exported, and I hope to work on the documentation over the next few weeks.

**Comment by TylerL-uxai** [comment]
Are there plans to make the daypicker clickable?

**Comment by majapw** [comment]
Hi @TylerL-uxai, I don't really understand your question. The `DayPicker` is clickable in that it has all these callback props for interaction with the dates (`onDayClick` for example) and takes in modifiers so that you can create your own logic to deal with that. If you want to the range logic, you can use the `DayPickerRangeController` as I mentioned above. I will eventually also create a `DayPickerSingleDateController` that will do that same thing for the single date logic. Does that answer your question?

**Comment by TylerL-uxai** [comment]
Thanks :) Yeah I just want it to turn blue and so I can ctrl+f the css style and find the value.
