### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by BrunoQuaresma** [airbnb/react-dates#262]
Here, the datepicker broken when i use in my smartphone. Currently, this is not supported? Or is a bug?

**Comment by majapw** [comment]
Hi @BrunoQuaresma can you give any more details on how it is broken? 

We used breakpoints here at Airbnb so our solution is to pass down different props (`numberOfMonth={1}` or `orientation={VERTICAL_ORIENTATION}`) once the screen size hits a certain breakpoint that we've determined to be a phone. We use `window.matchMedia` to check for screen size.

**Comment by JemarJones** [comment]
@majapw Can you provide an example of how you're using matchMedia to do that?

**Comment by ctrlaltdylan** [comment]
Interesting, thanks for sharing @majapw I was trying to use SCSS variables and CSS overrides but I'll try that approach instead.

**Comment by ctrlaltdylan** [comment]
To add to @majapw's answer, `orientation={react-dates/constants.VERTICAL_ORIENTATION}` does wonders combined with `withPortal={true}` or with `withFullScreenPortal={true}`

The next issue of responsiveness is easily changing the `.DateRangePickerInput` width without use of SCSS variables because unfortunately you can't use media queries to dynamically set SCSS variables (which would be so awesome if you could).

**Comment by rafinskipg** [comment]
Hi @ctrlaltdylan  your solution worked pretty well for me except for one issue.

When changing to 2 columns from 1 column the calendar dissapears. Until I click some arrow.

**Comment by ctrlplusb** [comment]
@rafinskipg I got around that by unmounting/remounting the date picker.  I use a `mode` state value to determine the orientation etc.  If this value is null I don't render anything.  When window size changes I first set it to null, and then set a timeout to hit after the next animationFrame (16ms) to set it to the desired value.  You get a small flash, but the component works as expected.

**Comment by majapw** [comment]
I think this issue has been addressed. :)

**Comment by heshamelmasry77** [comment]
The issue is not addressed correctly.
What you need to do @BrunoQuaresma is : 
first this orientation props take : horizontal, vertical and also verticalScrollable
maybe you create a constants file look like that:
``` 
export const HORIZONTAL_ORIENTATION = "horizontal";
export const VERTICAL_ORIENTATION = "vertical";
export const VERTICAL_SCROLLABLE = "verticalScrollable"; ```

then import it on your date picker JS file
``` import {
  HORIZONTAL_ORIENTATION,
} from './constants'; ```

and on your date picker : 
you use it like that : 
```  <DateRangePicker orientation={HORIZONTAL_ORIENTATION}/> ```
you can choose what ever choice you want for orientation.

one more thing you will face lets say you want on mobile to have the date picker one window but on desktop you want it two windows . at this point you need to use ``` numberOfMonths ``` prop.

to change between that mobile and desktop or maybe even tablet . You will use react responsive

so maybe you will create some responsive js file look like that:

``` import React from "react";
import Responsive from "react-responsive";
export const Mobile = props => <Responsive {...props} maxWidth={767} />;
export const Default = props => <Responsive {...props} minWidth={768} />; ```

then after than you change the  ``` numberOfMonths ``` on your component like that:
``` <Mobile>
                                    <DateRangePicker numberOfMonths={1} orientation={HORIZONTAL_ORIENTATION}/>
                                  </Mobile>
                                  <Default>
                                    <DateRangePicker numberOfMonths={2} orientation={HORIZONTAL_ORIENTATION}/> 
                                  </Default> ```
don't forget to import your responsive js file at your component.

And yeah good luck man hope i helped you.

**Comment by NVDan53** [comment]
many thanks

**Comment by feconroses** [comment]
I'm using `orientation={window.innerWidth > 700 ? HORIZONTAL_ORIENTATION : VERTICAL_ORIENTATION }` within `DateRangePicker`, so I can show the vertical orientation whenever the width of the window's layout viewport is less than 700 px.
