### ISSUE TITLE
Why use double-wrapped handlers in CalendarDay?

### ISSUE THREAD

**Issue by evandavis** [airbnb/react-dates#299]
The event handlers in `CalendarDay` are wrapped twice; first as an anonymous handler:
```js
onMouseEnter={e => this.onDayMouseEnter(day, e)}
```

and then again as a method on the class:
```js
onDayMouseEnter(day, e) {
  const { onDayMouseEnter } = this.props;
  onDayMouseEnter(day, e);
}
```

Why? What's the benefit vs doing either `onMouseEnter={e => this.props.onDayMouseEnter(day, e)}` inline or
```js
<div onMouseEnter={this.onDayMouseEnter} />

// and

onDayMouseEnter(e) {
  const { day, onDayMouseEnter } = this.props;
  onDayMouseEnter(day, e);
}
``` 
on the class?

**Comment by ljharb** [comment]
The important things to ensure are:
 - `this.props.onDayMouseEnter` is not called with a receiver (a `this` value) (the inline example you provided violates this)
 - as much logic as possible is in instance methods and not in arrows or bound functions, so that engine can optimize them (doing everything in an inline arrow would violate this)
 - event handlers should not have return values (your inline example violates this, and the direct reference doesn't ensure that nobody adds a return value later)

**Comment by evandavis** [comment]
@ljharb thank you! Points 1 and 2 make sense; things you need to ensure in a shared lib that I would not have considered in first-party code. 

However, in order to meet point 3, you'd need to add a `return;` to the inline arrows. As implemented, they'll still return a value if someone adds a return to the class methods. Is that an oversight, or am I missing something?

**Comment by ljharb** [comment]
When the inline arrows use explicit return - ie, the curly braces - they return `undefined` by default. It's only in the implicit return case that's a hazard.

In this case, we should be using curlies, but it's not super important because the instance methods also don't return anything.

**Comment by evandavis** [comment]
> In this case, we should be using curlies, but it's not super important because the instance methods also don't return anything.

Right, so in this case it's unnecessary wrapping, unless you add the braces to ensure returning `undefined`.

**Comment by ljharb** [comment]
True - that's a change we should make.

**Comment by evandavis** [comment]
Thanks!
