### ISSUE TITLE
Show full day names instead of short names

### ISSUE THREAD

**Issue by mayurgupta1991** [airbnb/react-dates#314]
@majapw 

Is it possible to show full week day names, instead of the short ones? When showing the calendar.

I mean instead of:

> Su Mo  Tu  We  Th  Fr  Sa,

Show these:

> Sunday  Monday  Tuesday  Wednesday  Thursday  Friday  Saturday

OR

> Sun   Mon  Tue   Wed   Thu   Fri  Sat

**Comment by nezed** [comment]
Probably you need `renderDay: PropTypes.func` introduced with #307

**Comment by majapw** [comment]
@mayurgupta1991 @nezed `renderDay` does not affect the week headers, it only affects the numerical days in the table. 

Right now this is no way to accomplish this. I also don't feel like it would be a good idea until https://github.com/airbnb/react-dates/pull/249 gets merged in because for most languages the full text would be too wide.

**Comment by majapw** [comment]
I'm going to say `won't fix` for now, but we can come back to this in the future.

**Comment by angusfretwell** [comment]
Hi @majapw, is this something that could be revisited now? We're keen to have three-letter day labels.
