### ISSUE TITLE
"Hover styling" breaks after last date selected.

### ISSUE THREAD

**Issue by herecydev** [airbnb/react-dates#33]
Using [this as an example](http://airbnb.io/react-dates/?selectedKind=DateRangePicker&selectedStory=default&full=0&down=1&left=1&panelRight=0) the turquoise highlighting that initially follows the mouse to show the time period no longer works after the last date is selected. After which point it gets "locked" on the last date and mouse movements have no impact on it. Selecting a new date will expand the time period correctly but the initial behavior can only be restored by clearing one of the dates.

**Comment by majapw** [comment]
This is intentional behavior! I can ask our designer for the precise reasoning, but this was a design choice not a bug. We wanted to leave the currently selected range on the calendar itself and make that very clear, even if you still had the calendar open and were clicking on another date. We will probably not change this behavior.
