### ISSUE TITLE
Allowing a date to be an end date but not a start date

### ISSUE THREAD

**Issue by zachfeldman** [airbnb/react-dates#357]
So this *seems* like a fairly important use case for a library like this, because when people book a room, they book a check in and check out date. Another user could conceivably want to check in on the day the first user has as a check out date. Meaning there are some dates that are valid checkOut dates but not valid checkIn dates.

Is there any way to handle this case with the react-dates library? Maybe an array/object of dates that are possible `endDate`s but not valid `startDates`? My apologies if I'm just missing this.

**Comment by majapw** [comment]
@zachfeldman Since `focusedInput` is a controlled prop, you theoretically have information about what input is focused at every render. You can pass in a different `isDayBlocked` method depending on this information. If you just have a minimum nights requirement for your, you can use the `minimumNights` prop for that. I'm imagining something as follows:

**Comment by zachfeldman** [comment]
@majapw urock! This worked well. I wasn't able to use the `START_DATE` constant in my code but otherwise this was just what I needed. Thanks again!

**Comment by majapw** [comment]
Sweet! If you do need to use any of the constants in the future, you can always do `import { START_DATE, VERTICAL_ORIENTATION } from 'react-dates/constants';`
