### ISSUE TITLE
Is it possible for the SingleDatePicker component to return the currently focused/rendered calendar month?

### ISSUE THREAD

**Issue by lferreira457** [airbnb/react-dates#360]
Mainly looking to use this to fix some performance issues & preload some date data close to the month being rendered rather than passing all my dates into the component.

**Comment by majapw** [comment]
So the idea I always had was that you could use `onPrevMonthClick` and `onNextMonthClick` to accomplish this. 

In theory, you know what the month is currently set to because either it is the default (`moment()` or the current month) or it is explicitly set by `initialVisibleMonth`. You can keep track of this in the state of your parent component and then increment/decrement in `onNextMonthClick`/`onPrevMonthClick` and use that information to preload stuff. Does that make sense?

We could also possibly return the visible month in those callbacks if that would make sense, but I'm not sure that that is strictly necessary. 

Please reopen this issue if the above instructions don't work for you!
