### ISSUE TITLE
question about debugging karma on firefox

### ISSUE THREAD

**Issue by thg303** [airbnb/react-dates#382]
I made a little change to the code and it leads to firefox break on a test-case failure, strange is it does not break any test on chrome. I wonder how do you guys debug karma tests in firefox? 
It took me almost 2 days now, Any idea would be appreciated.

**Comment by majapw** [comment]
We only run karma on firefox so this makes sense. Can you show us more details on the error you're seeing?

**Comment by majapw** [comment]
Hey @thg303, following up, I think we may have had some breaking karma tests on master for a while so it might not have been you. Was it something like `Attempted to wrap default which is already wrapped`? Because if so, those should be addressed now.

I'll close this for now, because my gut feeling is that you shouldn't be seeing this anymore! :) If it's still an issue, feel free to reopen this.
