### ISSUE TITLE
A question of minimal setup for DateRangePicker

### ISSUE THREAD

**Issue by Reaverart** [airbnb/react-dates#385]
Hey folks, thanks for awesome plugin, but I cant find a minimal setup for `DateRangePicker` in readme and all samples from storybook feels not correct because all of them uses your custom wrapper from examples folder, which not in export and its actually quite big to quickly understand how it works. 
So, the thing I'm looking for is minimal setup for `DateRangePicker`, peace. Btw am I right that I have to handle manually `focusedInput` prop?

**Comment by majapw** [comment]
Hi @Reaverart! 

For the minimum setup for each of the components, here's what you need:
*DateRangePicker:*
```jsx
<DateRangePicker
  startDate={this.state.startDate}
  endDate={this.state.endDate}
  onDatesChange={({ startDate, endDate }) => this.setState({ startDate, endDate })}
  focusedInput={this.state.focusedInput}
  onFocusChange={focusedInput => this.setState({ focusedInput })}
/>
```

*SingleDatePicker:*
```jsx
<SingleDatePicker
  date={this.state.date}
  onDateChange={date => this.setState({ date })}
  focused={this.state.focused}
  onFocusChange={({ focused }) => this.setState({ focused })}
/>
```

If you'd like to help improve the README to clarify this, I'd def appreciate your comments on #386. I'd also appreciate any thoughts you had on https://github.com/airbnb/react-dates/pull/387 (you can comment on the PR directly) to see if that change helps to clarify some of this confusion.

**Comment by Reaverart** [comment]
Thank for examples @majapw! I'll look into issues you mentioned. 
In general, I was confused because focus handling is something that feels like a "basic" functionality for me, so seems plugin cant be used out of the box and everybody have to write their own HOC to use it.
Dont you know why there is no "default" HOC in export that will fit most common cases?

**Comment by majapw** [comment]
Hi @Reaverart, that makes sense. This is at least part of the reason that I will be renaming `focusedInput` to `selectedInput`, because it's not traditional DOM focus that is being handled so much as which of the two dates are you selecting at the time. Focus may actually move to different elements (and def will after the a11y PR), but we still want to know which of the start date or end date we are selecting.

As for the reason there's no default HOC, it's largely due to the reason that fully controlled components with props and callbacks is kind of the React way to do things. When I first built this, we actually did originally have a component that tracked dates and focus in its internal state, but found that most of the time these were things that the parent needed to know about and specifically, not having access to those values led to gross React antipatterns like reaching into the DOM of the child components.
