### ISSUE TITLE
dateRangepicker UX is strange 

### ISSUE THREAD

**Issue by andyliuAccenture** [airbnb/react-dates#425]
May I use some range picker UX like pick the day before the range's start date, it auto enlarge the picked day range, now it work for the first time, but when I pick day before again, the day range Which highlighted disappear and refresh.
Can I use some API to fixed it?

**Comment by majapw** [comment]
You can explore the exact behavior of how the range is modified in https://github.com/airbnb/react-dates/blob/master/src/components/DayPickerRangeController.jsx#L132-L161, but the general gist is that it mostly depends on which input you have focused at the time. 

Which means if you have `start date` selected, it'll expand the range when you select a day before the currently selected start date, but if you have the end date selected, it'll have different behavior. The current behavior might be tweaked in the future, but it is by design.
