### ISSUE TITLE
Typing the date into the inputfield and have calendar update

### ISSUE THREAD

**Issue by dhcloud** [airbnb/react-dates#432]
Hi

I would like to be able to type the date into the input text field and have the calendar update as I'm typing. Is this functionality that's already build into react-dates? The blue(ish) translucent box seems to be strange UX (to me) as I can't see or move the cursor.

If anyone can show me how to do this I'd be very grateful.

Many thanks in advance

**Comment by majapw** [comment]
Hi @dhcloud, you can already type into any `react-dates` inputs:
![typing](https://cloud.githubusercontent.com/assets/1383861/24987833/e2fb2c68-1fb6-11e7-8ec5-138cf94c817a.gif)

However, as you noticed, the UI is a bit ick right now because it's a pretend input instead of a real input. I have a few ideas about this that will probably eventually make it into the repo. However, in the interim, you can type although there is no cursor and it only accepts strict date formats, ISO-9601 format (YYYY-MM-DD) and the moment L format in whatever locale you're in (MM/DD/YYYY for american english). You can also press the down arrow while the input is focused and navigate around the calendar using the arrow keys.

**Comment by andrii-yarmola** [comment]
@majapw 
but what if i want for user type format "dd/mm/yyyy" and "dd-mm-yyyy" to be valid for manually?
and transform both to my another format (displayFormat in props)
is it really strict and non-configurable ?
