### ISSUE TITLE
Setting props responsively doesn't always trigger layout calculations

### ISSUE THREAD

**Issue by nboliver** [airbnb/react-dates#443]
When changing properties such as `orientation` and `daySize` based on screen width, the DayPicker method `adjustDayPickerHeight` does not seem to fire consistently, so the calendar may have 0 height. It seems to work the first time and then not again. Maybe the condition that it is wrapped in here is blocking it?
https://github.com/airbnb/react-dates/blob/master/src/components/DayPicker.jsx#L224

Video of the issue: https://cl.ly/0c0j301T151L

As a related note, it would be awesome if there was a way to set the `daySize` as a % / fluid width. Doing so also does not allow the dimensions to update properly though.

**Comment by majapw** [comment]
Likely `adjustDayPickerHeight` should be called in more scenarios than are currently being called. If you want to push up a PR that calls it appropriately on your props change as well, I'd be happy to accept. I think it is likely that I haven't been able to account for all possible scenarios when writing the code. D:

As for setting `daySize` as a percentage, I don't really think the current structure really allows for that on the whole (the transition calculation/calendar month width setting and so on) and it just pushes down the burden of turning that into a pixel value in react-dates instead of in the parent application. We do use somewhat responsive to screen size day size values at Airbnb with the following code:
```
import {
  DAY_SIZE,
} from 'react-dates/constants';

const REACT_DATES_PADDING = 26;
const MAX_DAY_SIZE = 70;

let daySize;
if (typeof window !== 'undefined') {
  const scaledDaySize = Math.floor((window.innerWidth - REACT_DATES_PADDING) / 7);
  daySize = Math.min(scaledDaySize, MAX_DAY_SIZE);
} else {
  daySize = DAY_SIZE;
}
```

**Comment by nboliver** [comment]
Thanks for the quick reply. 

What do you think about this: https://github.com/airbnb/react-dates/pull/446

This way we should be able to call the `adjustDayPickerHeight` method from parent components as needed (ie. from `componentDidUpdate` etc.) and the specific logic for each update is left to the implementer instead of adding more logic to the `DayPicker` code.

**Comment by majapw** [comment]
@nboliver, like I mentioned on #446, reaching into the child component to access its methods is a pretty big antipattern (React is all about unidirectional information flow). I'd rather just have the `DayPicker` call `adjustDayPickerHeight` on all the prop changes that make sense.

**Comment by nboliver** [comment]
Yeah I agree that it is generally an antipattern to use a child's methods from a parent.
 
The desired UI is to have the calendar's container initially be hidden with `display: none`, and in this case the initial calculations are not accurate, so I was wondering about calling `adjustDayPickerHeight` when external UI changes happen, in addition to prop changes. 

However, if you're OK with just calling it on all prop changes, I can probably just force a prop change from above to trigger it.
