### ISSUE TITLE
DayPickerRangeController still displaying hover when blurred

### ISSUE THREAD

**Issue by chris-verclytte** [airbnb/react-dates#479]
Currently, the behaviour of the DayPickerRangeController is to hover days even when it has been blurred.
I would have expected it to be hoverable only when it has focus i.e. on [isHovered modifier](url) (https://github.com/airbnb/react-dates/blob/5b54d63c00fd18ddb4bfcef6a56fb297c1fd47f9/src/components/DayPickerRangeController.jsx#L261):
```javascript 
 isHovered(day) {
    const { focusedInput } = this.props;
    return (focusedInput === START_DATE || focusedInput === END_DATE) && isSameDay(day, this.state.hoverDate);
  }
```
Does this make sense ?

**Comment by majapw** [comment]
That seems reasonable to me! We primarily use the full `DateRangePicker` component at airbnb so we often don't catch little edge cases like this. :) Would be happy to accept a PR for this, although maybe it could just be:
```
isHovered(day) {
    const { focusedInput } = this.props;
    return focusedInput && isSameDay(day, this.state.hoverDate);
  }
```
since if `focusedInput` is truthy, then the `DayPickerRangeController` should be interactive.
