### ISSUE TITLE
Extending problem

### ISSUE THREAD

**Issue by DragorWW** [airbnb/react-dates#527]
simple example: I want change `DateRangePicker`, add logical in `DateInput`.
```js
//My step for extending `DateRangePicker`,
class MyDateRangePickerInput extends DateRangePicker {
  render () {
  // copy-past original code, and add my `DateRangePickerInputController`
  }
}

class MyDateRangePickerInputController extends DateRangePickerInputController {
  render () {
  // copy-past original code, and add my `DateRangePickerInput`
  }
}
class MyDateRangePickerInput extends DateRangePickerInput {
  render () {
  // copy-past original code, and add my `DateInput`
  }
}
// profit
```

**problems:**
- hard extending components
- much copy-past code
- hard supporting in future

My proposal: pass all children components as props in root component. example
```js
<DateRangePicker
  DateInput={MyDateInput}
/>
// profit
// or
<DateRangePicker
  DateRangePickerInput={MyDateRangePickerInput}
/>
```

What do you think about this?

**Comment by ljharb** [comment]
React components should never extend anything but React.Component/PureComponent - inheritance is not the proper way to share functionality.

What does your date input do that ours can not? Maybe we could add options to support your use case.

**Comment by majapw** [comment]
Hi @DragorWW,

We have a recommended path for customizing the inputs on the `DateRangePicker` component and that is to compose your own `DateRangePicker`-like component with your own inputs and the `DayPickerRangeController` component. You'll have to roll your own show/hide logic as well, but it should be relatively simple.

You can dig in the `DateRangePicker` source code and do a clean swap there, but it also probably has a lot of stuff you won't need as well. 

If you have specific needs that we could add as options, def open a new issue with those suggestions. O/w I'm going to close this issue as, again, the recommended path is composing a new component, rather than extending any of ours.
