### ISSUE TITLE
Change the start of the week to Monday

### ISSUE THREAD

**Issue by jkudish** [airbnb/react-dates#60]
Hey,

Great set of components here, love how easy it is to use! 

A small thing that I'd like to implement is to change the start of the week to Monday instead of Sunday. Is this currently possible? I don't see any documentation about it. If not, consider it a feature request!

Thanks

**Comment by ljharb** [comment]
[Moment docs](http://momentjs.com/docs/#/get-set/weekday/) imply that this is a locale-specific setting.

http://momentjs.com/docs/#/customization/ indicates that to override this, you should create your own moment locale - it looks like per http://momentjs.com/docs/#/i18n/changing-locale/ you can set this with:
```js
week: {
  dow: 1
}
```

Since moment already handles this, perhaps it's best to leave it to that lib?

**Comment by majapw** [comment]
Yeah! I don't think this is an issue for us to take on so much as for moment localization. For instance, if you change the locale to `es` you'll see that the week starts on Monday. 

Which means that for your own app you should be able to alter this using moment. I'm going to close this as won't fix.

**Comment by vladbalan** [comment]
Has anyone verified that it works? I set my `moment()._locale._week.dow` to `1`, but the calendar still displays `Su` as the first day of the week.

**Comment by majapw** [comment]
Hi @vladbalan, I am not sure that you can set the starting weekday in moment that way. I do know that if you look at pl.airbnb.com, the calendar starts on Monday:
<img width="631" alt="screen shot 2017-01-27 at 10 05 34 pm" src="https://cloud.githubusercontent.com/assets/1383861/22394729/d6733b6c-e4dc-11e6-811b-74b1baecc282.png">

This was done by calling `moment.locale('pl')`. Perhaps the parentheses are throwing it off. That is a moment object instead of the general moment class.

**Comment by elado** [comment]
Just pasting here the needed locale update to achieve this:

```js
moment.updateLocale('en', {
  week: {
    dow: 1,
  },
})
```

**Comment by ezequiel9** [comment]
Use date.startOf('isoWeek'); instead of date.startOf('week');

**Comment by rodrigoespinozadev** [comment]
> Use
> `date.startOf('isoWeek'); instead of date.startOf('week');`

Thanks for the help

**Comment by gautam-pahuja** [comment]
Doing this:

```
moment.updateLocale('en', {
  week: {
    dow: 1,
  },
})
```

and then This:
```
moment.weekdays() 
```

gives me:
["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]

**Comment by prabhsaran** [comment]
pass in true to the weekdays function 
`moment.weekdays(true)` 
so they are returned in locale specific order

**Comment by thanhtuanapril1** [comment]
I have same problem. Anyone success to change the start of week to Monday?

**Comment by thanhtuanapril1** [comment]
> I have same problem. Anyone success to change the start of week to Monday?

moment.updateLocale('es', {
    week: {
        dow: 1, // Monday is the first day of the week
        doy: 4, // The week that contains Jan 4th is the first week of the year
    }
});

Tried with this but not working
