### ISSUE TITLE
Open upwards?

### ISSUE THREAD

**Issue by balajivenkatesh** [airbnb/react-dates#648]
My date picker sits at the bottom of the page. Is it possible to make the calendar open upwards?

**Comment by timhwang21** [comment]
I've actually done this solely with CSS. Because the calendars are absolutely positioned, it's a matter of:

1. Moving the calendar down `height of calendar + distance of calendar from middle of input` pixels
2. Flipping the little arrows pointing at the input and moving them down the appropriate distance

The way we do it, we check if the calendar widget is a certain distance away from the bottom of the screen. If it's too close, we add a classname and make the calendar open upwards.

Example: <img width="1083" alt="screen shot 2017-07-26 at 6 20 26 pm" src="https://user-images.githubusercontent.com/5831434/28646328-27509a0e-722f-11e7-8102-07a46a147c5b.png">

@ljharb do you think a PR that changes calendar positioning based on some prop would be good?

**Comment by ljharb** [comment]
It seems reasonable, but @majapw's in charge here.

**Comment by majapw** [comment]
Yeah I think this would be a legit prop to add!
