### ISSUE TITLE
Selected dates not painted when load more months

### ISSUE THREAD

**Issue by cagiraudo** [airbnb/react-dates#705]
Hi, i couldn't find the issue so i don't know if it's a known issue.

When you open the datepicker in mobile vertically and you load more months it doesn't paint when you select the date.

The same error is present in airbnb.com when you visit with mobile:

In this image you can see how it paint when i select the first date in the months loaded at begining:
![seleccion_031](https://user-images.githubusercontent.com/19225821/30166168-db5bfafc-93b8-11e7-853e-0a7171e88878.png)

And here you can see how it doesn't paint when i select a date in a month that was loaded after
![seleccion_032](https://user-images.githubusercontent.com/19225821/30166205-fc572ea2-93b8-11e7-82f1-ddc90ba631a4.png)

**Comment by majapw** [comment]
Yup! Need to fix the vertical scrollable datepicker. X_x

**Comment by crash7** [comment]
Hi @majapw 
,
I did some digging here, and found that the problem is related to [this condition](https://github.com/airbnb/react-dates/blob/master/src/components/DayPickerRangeController.jsx#L641-L643):
```
addModifier(updatedDays, day, modifier) {
    ....
    if (!day || !isDayVisible(day, currentMonth, numberOfMonths, enableOutsideDays)) {
      return updatedDays;
    }
```
`isDayVisible` is not considering the number of visible months in the calculation to validate the date.

Adding something like `numberOfMonths = Object.keys(visibleDays).length;` a couple of lines above fixes this particular problem but problably there is a better aproach to avoiding overriding a prop (seems hacky to me).
Example:
```
    if (orientation !== VERTICAL_SCROLLABLE) {
      currentMonth = currentMonth.clone().subtract(1, 'month');
      numberOfMonths += 2;
    } else {
      numberOfMonths = Object.keys(visibleDays).length;
    }
    if (!day || !isDayVisible(day, currentMonth, numberOfMonths, enableOutsideDays)) {
      return updatedDays;
    }
```

I checked the tests and adding this doesn't break anything but didn't submit a PR yet.

**Comment by Daniellt1** [comment]
Hi @majapw, 

Any updates on this one?

**Comment by The-Code-Monkey** [comment]
@majapw has this been fixed yet?

**Comment by Daniellt1** [comment]
Is it fixed for `DayPickerSingleDateController` as well? I am still getting the same issue on `react-dates@18.1.0`.
