### ISSUE TITLE
RTL Nav Bug

### ISSUE THREAD

**Issue by SimeonC** [airbnb/react-dates#762]
I'm unsure as to whether this is a bug or as intended (I'm new to working with RTL).

When using custom `navNext` and `navPrev` elements and `isRTL` the icons appear to be incorrectly ordered due to the login https://github.com/airbnb/react-dates/blob/master/src/components/DayPickerNavigation.jsx#L62-L96

```jsx
<DayPicker
  date={datetime || moment()}
  onDateChange={this.onDateChange}
  numberOfMonths={1}
  hideKeyboardShortcutsPanel
  enableOutsideDays
  isOutsideRange={isOutsideRange}
  navPrev={<Icon name={'chevron-left'} />}
  navNext={<Icon name={'chevron-right'} />}
  isRTL
/>
```

Results in:
![image](https://user-images.githubusercontent.com/1085899/31431954-27df21b2-aeb0-11e7-839a-9bc5f0522d72.png)

I'm not sure if this is intended or not but my workaround is currently (using dynamically changed isRTL):
```jsx
navPrev={<Icon name={isRTL ? 'chevron-right' : 'chevron-left'} />}
navNext={<Icon name={isRTL ? 'chevron-left' : 'chevron-right'} />}
isRTL={isRTL}
```

I've tested this on 12.7.0, I can't try it on 13.x versions yet as we use sass not inline styles and I don't have the time to figure out how to implement the new themeing system (doesn't seem hard just quite a bit time consuming).

**Comment by majapw** [comment]
HI @SimeonC, this is not a bug. 

The reason that this is not a problem with the default navigation is that we do this flipping for you (see https://github.com/airbnb/react-dates/blob/master/src/components/DayPickerNavigation.jsx#L69-L71 and https://github.com/airbnb/react-dates/blob/master/src/components/DayPickerNavigation.jsx#L85-L87).

We do not do this for a custom icon because that's not an assumption we can make. If you are going right-to-left, your next icon to point to the left. If you are in a left-to-right context, your next icon should point to the right, so your workaround is actually the solution.
