### ISSUE TITLE
Daylight saving time in Brazil and duplicated October 15 

### ISSUE THREAD

**Issue by derekstavis** [airbnb/react-dates#776]
Hey,

Selecting October 15 or 16 in America/Sao_Paulo timezone gives me duplicated days:

![peek 2017-10-16 14-35](https://user-images.githubusercontent.com/1611639/31623806-64db9a50-b27f-11e7-9e52-0626620e32ed.gif)

This is a new issue originally reported by @felquis in #55.

**Comment by felquis** [comment]
Alright, at airbnb.com you cannot reproduce it, because day 15 is out of range.

**Comment by majapw** [comment]
But are two October 16s visible?

**Comment by majapw** [comment]
Oh jokes it's only when selected. That's really weird!

**Comment by darakeon** [comment]
The real problem is with endOf function of moment. At Oct 15th, the endOf was pointing to GMT 2:59:59. At Oct 16th, the start was GMT 2:00:00. So there was an hour that, according to moment, belongs to two days, when it should belong only to Oct 16th. Fixed it making the endOf of Oct 15th be one millisecond before the start of Oct 16th.
