### ISSUE TITLE
DateRangePicker initialises itself outside viewport width

### ISSUE THREAD

**Issue by isaachinman** [airbnb/react-dates#80]
As you can seen in the screenshot below, the DateRangePicker component seems to (sometimes) initalise itself without regard to viewport width. In my case, it is actually placing itself in such a way that my entire page breaks (the dark edge is the edge of my viewport, were it not to be expanded by the DateRangePicker).

No, I am not initialising it in a hidden component or anything like that - I am using it completely as intended/expected.

This happens even at screen widths as high as 1000px, if the input is placed close enough to the edge.

In fact, this impacts my entire page _even when the datepicker is closed_, because of the use of `visibility: hidden` instead of `display: none`.

Sorry for not including a live example, but I haven't yet found a decent sandbox to use for npm/es6 stuff.

![screen shot 2016-09-13 at 13 28 52](https://cloud.githubusercontent.com/assets/10575782/18472219/5dd050dc-79b6-11e6-94f9-c9e1793ba1a6.png)

**Comment by majapw** [comment]
This is related to https://github.com/airbnb/react-dates/issues/71 (although that solution I think is only a stopgap).

Ideally we should have a totes responsive component that can see if it is overflowing and adjust itself accordingly. That's not there yet (soon! well, relatively). In the mean time you can override the position on the `.DateRangePicker__picker` (originally set at https://github.com/airbnb/react-dates/blob/master/css/DateRangePicker.scss#L24) in your own stylesheet. You'll probably want to override the `:before` and `:after` positioning styles as well (https://github.com/airbnb/react-dates/blob/master/css/DateRangePicker.scss#L56:L86).

https://github.com/airbnb/react-dates/blob/master/css/DateRangePicker.scss#L56:L86).

This is a bummer:
> In fact, this impacts my entire page even when the datepicker is closed, because of the use of `visibility: hidden` instead of `display: none`.

We use `visibility` over `display` right now so that we can do a height calculation while the datepicker is still closed but the DOM has been rendered.  I want to move away from this... but I think that will have to wait until we manage to get a `react-with-styles` implementation out (which is tricky, but in the works).

**Comment by isaachinman** [comment]
I don't think this the sort of thing one could fix with CSS overrides, and to be honest this library is not production ready until this is addressed.

Lots and lots of similar kinds of components exist out in the wild that set themselves appropriately!

**Comment by majapw** [comment]
Fixed in v3.3.2
