### ISSUE TITLE
Avoid initial input focus

### ISSUE THREAD

**Issue by gugadev** [airbnb/react-dates#830]
I pass `null` to `focusedInput` property and works but I get an error:

> Warning: Failed prop type: The prop `focusedInput` is marked as required in `Content`, but it's value is `null`.

There is any way to avoid this error?

**Comment by majapw** [comment]
What the fudge is `Content`? Can you share the full stacktrace?

are you importing the focusedInput proptype anywhere and then setting `.isRequired` on it? Because that would (unfortunately) break things.

**Comment by ljharb** [comment]
I’m not sure why; `.isRequired` returns a new validator, it doesn’t mutate the original one.

**Comment by majapw** [comment]
Right but putting `.isRequired` on `PropTypes.oneOf([START_DATE, END_DATE])` would fail for a value of `null`. 

Because I never put in the effort to figure out how to get `explicitNull` working.

**Comment by majapw** [comment]
I think this is due to a prop type validation on a component above `react-dates`. None of our components have a required focusedInput which is why you are able to pass null. If you want to do the same for your Content component, I think you will have to remove the `isRequired` flag on its prop type definition. :) Let me know if you have more Qs!
