### ISSUE TITLE
react-portal v4?

### ISSUE THREAD

**Issue by lencioni** [airbnb/react-dates#860]
v4 is out and supports only React 16+, but react-dates does not allow it to be used. Is there a way to add support for v4 here?

**Comment by majapw** [comment]
@lencioni Because we do not only support React v16, `react-portal@4` is not really an option for us right now. There's some great discussion in https://github.com/tajo/react-portal/issues/180 that might allow us to upgrade eventually but we're blocked for now.

**Comment by lencioni** [comment]
I'm not super familiar with react-portal. Do you know if v4 has the same API as v3? If so, perhaps the package.json version range could be changed to `^3.1.0 || ^4.0.0`?

**Comment by brucewpaul** [comment]
it seems as though the api is the same? https://github.com/tajo/react-portal/issues/180#issuecomment-347377358

**Comment by majapw** [comment]
@brucewpaul @lencioni it looks like the API is not the same. Before we were able to do `import Portal from 'react-portal';` It look like with the addition of `PortalWithState`, you now have to `import { Portal } from 'react-portal'`;

Potentially we could deep import. Although it looks like the file is at `build/portal.js` in 3.0.0 and `lib/Portal.js` in 4.0.0 so that's not great. :/

**Comment by brucewpaul** [comment]
ya, the api definitely is not the same. additionally, the props that were being used in 3.1.0 aren't being used/passed to anything in 4.0.0

**Comment by ljharb** [comment]
we can only use v4 if react-portal ships a version that allows all the React versions we support; otherwise we’re on v3 for a long while.

**Comment by ljharb** [comment]
Closed in #888.
