### ISSUE TITLE
Input element overflows DateInput Div

### ISSUE THREAD

**Issue by AmalJossy** [airbnb/react-dates#965]
![dates](https://user-images.githubusercontent.com/19892510/35194824-aa05adda-fedf-11e7-94fb-ce9c04f23292.PNG)
The input element within the DateInput div element overflows the parent if the `box-sizing:borderbox;`
is not set to it. In the storybook, all elements inherits `box-sizing:borderbox;` in _storybook.scss which may not be provided in all projects explicitly

**Comment by majapw** [comment]
Hi @AmalJossy, there's a note on this in the README in the initialize section - https://github.com/airbnb/react-dates#initialize

Specifically, we state that:
```
Note: This component assumes box-sizing: border-box is set globally in your page's CSS.
```

We had a lot of discussion about this but it seemed like a better strategy to expect border-box styling above the datepicker level rather than to add it to every single component in the react-dates library. :/ 

If you have feedback on this, we'd def be open to it, but I think for rn this is a wontfix.
